############################### Basic Information ###############################
info:
  name: Volantis
  version: '2.1.4'
  docs: https://volantis.js.org/
  cdn: # To use CDN, write 'use_cdn: true' in 'blog/_config.yml'.
    # css: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1.4.3/css/style.css
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1.4/js/app.js


############################### Style ###############################
style:
  max_width: 1080px # Sum of body width and sidebar width
  navbar:
    height: 56px
    effect: [shadow, floatable] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow, floatable] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      copy_btn: true
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
  gap:
    h2: 48px # Spacing above H2 (only px unit)
    h3: 32px # Spacing above H3 (only px unit)
    h4: 16px # Spacing above H4 (only px unit)
    line: 1rem # Paragraph spacing
    inline: .5rem # Paragraph spacing within a block
  border_radius:
    card: 12px
    codeblock: 4px
    searchbar: 8px
    button: 4px
  tabs:
    shadow_level: 1 # 0, 1, 2, 3
  fontsize:
    root: 16px
    h1: 1.625rem
    h2: 1.375rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: 1rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
  fontfamily:
    bodyfont:
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    codefont:
      name: 'Monaco'
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
      weight: normal
      style: normal
  color:
    # site: '#E84D3B'
    # site_inner: '#FFCE48'
    # theme: '#E84D3B'
    site: '#64c79b' # Website background color
    site_inner: '#FFF33F' # Text color inside the website background
    site_features: '#FFFF00' # Text color inside the website background
    site_features_hl: '#FFF33F' # Text color inside the website background
    card: '#138B73' # Card background color
    text: '#FFFFFF' # The color of the text on the card.
    theme: '#F1C40F' # Main color
    link: '#00C75D' # Link color
    hover: '#00FA75' # Link highlight color
    inner: '#FFFFFF' # Text color inside the button
    block: '#16A286' # Block color
    inlinecode: yellow # Inline code color
    codeblock: '#2C3E50' # Codeblock color
    p: '#F0FFF7' # Paragraph color




############################### Layout ###############################
cover:
  scheme: blog # docs, blog
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  logo: # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/256/google_logo.png
  title: ç©ºè¡—å¬é›¨
  subtitle: "Nero Song's life blog"
  search: # search bar placeholder
  features:
    - name: åšæ–‡
      icon: fas fa-pen-nib
      url: /
    - name: å½’æ¡£
      icon: fas fa-archive
      url: /archives
    - name: äº§å“
      icon: fas fa-code
      url: /product
    - name: å®éªŒå®¤
      icon: fas fa-flask
      url: /lab
      # rel: external nofollow noopener noreferrer
      # target: _blank
    - name: å…³äº
      icon: fas fa-info-circle
      url: /about


# Navigation Bar
navbar:
  logo: # choose [img] or [icon + title]
    img: 
    icon: 
    title: ç©ºè¡—å¬é›¨
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    # This menu will be displayed on the laptop or desktop.
    on_desktop:
      - name: åšæ–‡
        icon: fas fa-pen-nib
        url: /
      - name: å½’æ¡£
        icon: fas fa-archive
        url: /archives
      - name: äº§å“
        icon: fas fa-code
        url: /product
      - name: å®éªŒå®¤
        icon: fas fa-flask
        url: /lab
      - name: å…³äº
        icon: fas fa-info-circle
        url: /about
    # This menu will be displayed on the mobile.
    on_mobile:
      - name: åšæ–‡
        icon: fas fa-pen-nib
        url: /
      - name: å½’æ¡£
        icon: fas fa-archive
        url: /archives
      - name: äº§å“
        icon: fas fa-code
        url: /product
      - name: å®éªŒå®¤
        icon: fas fa-flask
        url: /lab
      - name: å…³äº
        icon: fas fa-info-circle
        url: /about
  search:   # Search bar placeholder



layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # æ–‡ç« åˆ—è¡¨ï¼ˆä¸»é¡µã€è‡ªå®šä¹‰çš„åˆ—è¡¨ï¼‰å¸ƒå±€
  on_list:
    # åˆ—è¡¨ä¸­æ¯ä¸€ç¯‡æ–‡ç« çš„metaä¿¡æ¯
    meta: [title, author, category, date, wordcount, top]
    # åˆ—è¡¨ç±»é¡µé¢çš„ä¾§è¾¹æ 
    sidebar: [blogger, category, tagcloud, repos]
    # read more button
    readmore: Read More <i class="fas fa-chevron-right"></i>
  # é¡µé¢å¸ƒå±€
  on_page:
    # æ–‡ç« é¡µé¢ä¸»ä½“å…ƒç´ ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨é¡µé¢çš„Front-matterä¸­è®¾ç½®
    body: [article, comments]
    # é»˜è®¤çš„metaä¿¡æ¯ï¼Œæ–‡ç« ä¸­æ²¡æœ‰é…ç½®åˆ™æŒ‰ç…§è¿™é‡Œçš„é…ç½®æ¥æ˜¾ç¤ºï¼Œè®¾ç½®ä¸ºfalseåˆ™ä¸æ˜¾ç¤º
    # å…¶ä¸­ï¼Œtitleåªåœ¨headerä¸­æœ‰æ•ˆï¼Œmusicå’Œthumbnailæ— éœ€åœ¨è¿™é‡Œè®¾ç½®ï¼Œæ–‡ç« ä¸­æœ‰åˆ™æ˜¾ç¤º
    # å¦‚æœtagsæ”¾ç½®åœ¨meta.headerä¸­ï¼Œé‚£ä¹ˆåœ¨poståˆ—è¡¨ä¸­ä¸æ˜¾ç¤ºï¼ˆå› ä¸ºå¡ç‰‡ä¸‹æ–¹å·²ç»æœ‰äº†ï¼‰
    meta:
      header: [title, author, category, date, top]
      footer: [updated, tags, btns, share]
    # æ–‡ç« é¡µé¢çš„ä¾§è¾¹æ 
    sidebar: [toc, related_posts]
  # æ–‡ç« å¸ƒå±€ï¼Œå‚æ•°ç»§æ‰¿è‡ª on_page
  on_post:
    # æ–‡ç« é¡µè„šï¼Œè‡ªåŠ¨åœ¨æ¯ä¸€ç¯‡æ–‡ç« æœ«å°¾æ·»åŠ 
    article_footer: [copyright]
  # å…¶ä»–çš„é¡µé¢å¸ƒå±€æš‚æ—¶ç­‰äº on_list


# meta library
meta:
  # æ–‡ç« æ ‡é¢˜
  title: # æš‚æ— é…ç½®
  # é»˜è®¤æ–‡ç« ä½œè€…ï¼ˆå¯åœ¨front-matterä¸­è¦†ç›–ï¼‰
  author:
    avatar: https://cdn.jsdelivr.net/gh/NeroSong/cdn-blog/avator.jpg
    name: è¥¿æµ·å²¸æ€»ç£
    url: /
  # æ–‡ç« åˆ›å»ºæ—¥æœŸ
  date:
    icon: fas fa-edit
    title: 'å‘å¸ƒäºï¼š'
    format: 'll' # æ—¥æœŸæ ¼å¼ http://momentjs.com/docs/
  # æ–‡ç« æ›´æ–°æ—¥æœŸ
  updated:
    icon: fas fa-save
    title: 'æ›´æ–°äºï¼š'
    format: 'll' # æ—¥æœŸæ ¼å¼ http://momentjs.com/docs/
  # æ–‡ç« åˆ†ç±»
  category:
    icon: fas fa-folder-open
  # æ–‡ç« ç½®é¡¶
  top:
    icon: fas fa-angle-double-up
  # æ–‡ç« æµè§ˆè®¡æ•°
  counter:
    icon: fas fa-eye
  # æ–‡ç« å­—æ•°å’Œé˜…è¯»æ—¶é•¿
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # æ–‡ç« æ ‡ç­¾
  tags:
    icon: fas fa-hashtag
  # åˆ†äº«
  share:
    - id: qq
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
    - id: qzone
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qzone.png
    - id: weibo
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
    # - id: qrcode # å½“idä¸ºqrcodeæ—¶éœ€è¦å®‰è£…æ’ä»¶  npm i -S hexo-helper-qrcode
    #   img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/wechat.png
  # é“¾æ¥
  btns:
    edit:
      icon: fas fa-edit
      title: åœ¨GitHubä¸Šç¼–è¾‘æ­¤é¡µ
      color: '#888'
    repo: # æºç é“¾æ¥
      icon: fas fa-file-code
      title: æºç 
      color: '#508EF2'
    bug: # BUGåé¦ˆé“¾æ¥
      icon: fas fa-bug
      title: BUG
      color: '#FE5F58'
    doubt: # ç–‘é—®é“¾æ¥
      icon: fas fa-question-circle
      title: ç–‘é—®
      color: '#FFBD2B'
    idea: # å»ºè®®é“¾æ¥
      icon: fas fa-lightbulb
      title: å»ºè®®
      color: '#3DC550'
    faq: # FAQé“¾æ¥
      icon: fas fa-comments
      title: FAQ
      color: '#29B1C9'
    feedback: # åé¦ˆé“¾æ¥
      icon: fas fa-comment-dots
      title: åé¦ˆ
      color: '#1BCDFC'

# widget library
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  blogger:
    class: blogger
    display: [desktop] # [desktop, mobile]
    avatar: https://cdn.jsdelivr.net/gh/NeroSong/cdn-blog/avator.jpg
    title:
    subtitle:
    jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: æœ¬æ–‡ç›®å½•
    list_number: false
    min_depth: 2
    max_depth: 5
  # ---------------------------------------
  # category widget
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: æ–‡ç« åˆ†ç±»
      url: /blog/categories/
  # ---------------------------------------
  # tagcloud widget
  tagcloud:
    class: tagcloud
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: çƒ­é—¨æ ‡ç­¾
      url: /blog/tags/
    min_font: 14
    max_font: 24
    color: true
    start_color: '#BDC3C7'
    end_color: '#FFFFFF'
  # ---------------------------------------
  # related posts widget
  related_posts:
    class: related_posts # npm i -S hexo-related-popular-posts
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-bookmark
      title: ç›¸å…³æ–‡ç« 
    max_count: 5
  # ---------------------------------------
  # copyright widget (valid only in articles)
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true
    permalink: 'æœ¬æ–‡æ°¸ä¹…é“¾æ¥æ˜¯ï¼š'
    content:
      - 'åšå®¢å†…å®¹éµå¾ª ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™… (CC BY-NC-SA 4.0) åè®®'
      - permalink
  # ---------------------------------------
  # qrcode widget
  donate:
    class: qrcode
    display: [desktop, mobile] # [desktop, mobile]
    height: 64px  # Automatic height if not set
    fancybox: true
    images:
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/

  repos:
    class: text
    display: [desktop] # [desktop, mobile]
    header:
      icon: fab fa-github
      title: å°è¯•ä¸€ä¸‹
      url: https://github.com/xaoxuu/
    content:
      - 'ä»¥ä¸‹éƒ½æ˜¯äº›éå¸¸æœ‰è¶£çš„å°ç©æ„å„¿~'
      - 'æ²¡å‡†èƒ½å¤Ÿå¸®åˆ°ä½ ğŸ˜'
      - '[<img src="https://cdn.jsdelivr.net/gh/NeroSong/cdn-blog/intro_icon_gk.png" height="60px">](https://www.coolapk.com/apk/com.nerosong.godknows)'
      - '[<img src="https://cdn.jsdelivr.net/gh/NeroSong/cdn-blog/intro_icon_xlw1.png" height="55px">](https://essay.1ts.fun)'


footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [social, license, info, copyright]
  social:
    - icon: fas fa-rss
      url: /atom.xml
    - icon: fas fa-envelope
      url: mailto:bravolavita@gmail.com
    - icon: fab fa-github
      url: https://github.com/NeroSong
  copyright: 'Copyright Â© 2018-2020 è¥¿æµ·å²¸æ€»ç£ â¤ï¸ æ–°è¯­é—®æ¹– | [é™‡ICPå¤‡19003414å·](http://www.beian.miit.gov.cn)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'


############################### SEO ###############################
seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter


############################### Plugins ###############################
plugins:
  # Required plugins:
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.4/dist/jquery.min.js

  ######## Plugins to improve loading speed:
  # Preload (The menu's url must end with â€˜/â€™)
  instant_page: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/instant_page.js

  ######## Plugins to optimize the experience:
  # Picture Zoom
  fancybox:
    css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # Page Scrolling Animation
  scrollreveal: #https://cdn.jsdelivr.net/npm/scrollreveal@4.0.5/dist/scrollreveal.min.js

  # Codeblock Copy Button
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  # mathjax
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  ######## Plugins for SEO:
  # Traffic statistics (very slow loading)
  busuanzi: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

  # npm i --save hexo-wordcount
  wordcount: #true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # Typing Effects
  comment_typing: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 20000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/NeroSong/cdn-blog/under_the_overpass_x1.jpg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: false
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 3175833810    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 340px # list max height
    list_folded: true




############################### Comments ###############################
comments:
  title: <i class='fas fa-comments'></i> è¯„è®º
  subtitle:
  service: valine # valine, disqus, gitalk, livere
  valine:
    appId: VLYFtItf6JwzUhQhaVSwVOpo-gzGzoHsz
    appKey: IEfO3BDaQ7xM7wkGQQWcYFS3
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0/js/valine.js
    path: # All pages use the same path (share the same comments data)
    meta: nick,mail,link #valine comment header info
    placeholder: æƒ³è¦åä¸ªæ§½~ # valine comment input placeholder(like: Please leave your footprints )
    avatar: mp # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    verify: true # valine verify code (true/false)
    notify: true # valine mail notify (true/false)
    lang: zh-cn
    highlight: true
    visitor: false # unavailable for now...
  disqus:
    shortname:
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin: # []
  livere:
    uid:




############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i -S hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:
